### ISSUE TITLE
Game Of Life

### ISSUE THREAD

**Issue by davidpcahill** [ErikBot42/VCB-blueprints#1]
Could you please add an assembled game of life vcb please? I lined up the module in your repo but it doesn't seem to be working as expected. I am likely doing something wrong or something is missing.

**Comment by ErikBot42** [comment]
It needs a 1 tick pulse to update the state, here is an example setup: 

`KLUv/aBgSAIAtC0AlAIAACo1Qf+udP//Lkdd/004Pv9meI7//8ZjY/KmAP//ogCiADhNR2P/n4SaqNMfSA/jGoAwRUEcA1MRFROAAwAQIAZgCJAIGAtICHgJHAKAgFCQEAAAAAAIglFvTQAp3WCit9VFgJdtN/V3uFhS+J8mBYnQQC7+mOLGRNVtPEGxvyIrjKZUe4scGB9xJGyRW63eIgfGRxwJW+S21VvkwPiII2GL3LZ6ixwYH3EkbJHblt4iB8ZHHAlb5LbVW+TA+IgjYYvctnqLHBgfcSRskdtW3yIHxkccCVvkttVb5MD4iCNhi9y2eoscGB9xJGyR21ZvEQfGRxwJW+S21VvkwPiII2GL3LZ6ixwYH3EkbJHbVm+RA8ZHHAlb5LbVW+TA+IgjYYvctnqLHBgfcSRskdtWb5FDxkccCVvkttVb5MD4iCNhi9y2eoscGB9xJGyR21ZvkQPjRRwBN8TdtTjxKXTRuLT6Axqb2lpZtFxJ+KNfELd4Trw+6GIq+IOJ7lYXUwcSlwDXiHTQq15C2gk86L/8f78+2kBEqR8p2/PDTfZNvUi26gsdUZY+B8S6fK/F9gJ6XfTaQevqq4l+JK/GJTOst8KK9oOJzrsmHGdu1GG4u6ES4IUO58t6b7cDkXa/9kd6mnE6ub5ogikzdHaT+WjIT1kWqGERXHWtkJzsNbkgJzjc1LC4WK16KyQv81sW/CQJchYWFpNVd4XkZK/JBTnB4aaGxcVq1VsheZmfZcFPkiBnYWExWXVXSE72mlyQExxualhcrFa9FZKX+S0LfpIEOQsLi8mqu0JystfkgpzA4aaGxcVq1VsheZnfsuAnSZCzsLCYrLorJCd7TS7ICQ43NSwuVqveCsnL/JYFP0mCnAsLi8mqu0JystfkgpzgcFPD4mK16q2QvMxvWfCTJMhZWFhMVt0VkpO9JhfkBIebGhYXq1VvhaTL/JYFP0mCnIWFxWTVXSE52WtyQU5wuKlhcbFa9VZIXua3LPhJEuQsLCwmq+4KycleJRfkBIebGhYXq1VvheRlfsuCnyRBzsLCYrLqrpCc7DW5ICc43NSwuFiteiskL/NbFvykEuQsLCwmq+4KyclekwtygsNNDYuLrbpbX7NqeQWO9AmmfyuvInO0ddTnjU3YheSsB1Wv2hq8qfoar9srW8F36hNzjJ3ore9IYyLAK20zGmCIT9h2UhaN7ItzcHcvgx47RQT4+tePz0gFpRuz567pXRxpNusVzUpMnuokwMtmvjS7l1ZFt8jTkQRcRgxon5CJTXtxWnDVxqxBaHbUdKCdFBv/QiLrizxnbymVBXipndLdHDX1IQvNKAKMZN6w1bI4wGvL2MJi8xfjz4PRYMA7kj7SYbVzO59S2+uUhtT+F0N/vH53KNzWsqXi+S/VrbUW2eHgQWtKvatrSMkHyTbxlR02UmU6/eka/Udyn4a+xz4EeGkM5g5O1lwwybseiSM2sp4754jk74iPyVuqTQx/ZBvPdeOK9JcaYylyV8KoBP/NA2VZa+idH/gir1Js5eIZ8Rr8kaLFu1/ucuTt2+FZum3MOji70V1GRO7ugXRdyKXl9JHhkDnx+AglVhbgpWVXU1a1jnUZSPcr6WG6XI8cD365DBsUAV6w5nbN5Xj1ll1qgCUVGkh37ljkgUTuK1ISGP4ZLewWbj0N8FLPYrmr7deZBrHAPs89FqbcUeM7wAv8Atc2vR0V/I5zFNm+R2wfjgcfd5ka3AFekM1Mp+2lsqsxHm+5I8c1tiUzbyFsZSjAK9QnydZTwu+E7E/oi0GPjgW5dyhbVwR46ep+YXiEMZdx851qEQR4rcV2DJS2D5Tc15E7A0d+7MSbA4dw+gMP6vhjvRQW4GX7GeOPV0/EXt1j3P5M/zja752V/V8j3pG2phjgRZduqD+qmSqOSWz7o3dhCX6Wt+zTebsTOESY5aKoQ8d/ZfX8By0EACg4AAAAADogYQeFBaWpFA4FCyxAGEDBAgsQBFCwwAKEARQUBSNZ8GOKQMeDexH9Cn6/n4Z8s4IEgdNKEc5RA0gAoY8+BTUGVEHn7UkQokBAiEICQhQICFFAQISCF0IUEhCiQECIQgIiFLwQopCAEAUCQhQSEKHghRCFBIQoEBCigM7w7xUCAAAAuwAAAAIAAADIAAAAAgAAAGBIAgACAAAAAAABAA==`
